"""align ORM indexes and archive metadata

Revision ID: 55a8c9364506
Revises: 0017_report_is_demo
Create Date: 2026-09-30 18:26:18.152395+00:00

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "0018_archive_metadata"
down_revision: Union[str, None] = "0017_report_is_demo"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(
        op.f("ix_forecast_advisories_valid_from"),
        "forecast_advisories",
        ["valid_from"],
        unique=False,
    )
    op.create_index(
        op.f("ix_forecast_advisories_valid_until"),
        "forecast_advisories",
        ["valid_until"],
        unique=False,
    )
    op.create_index(
        op.f("ix_realtime_outbox_next_retry_at"), "realtime_outbox", ["next_retry_at"], unique=False
    )
    op.drop_index(op.f("ix_users_email"), table_name="users")
    op.drop_index(
        op.f("idx_weather_reports_archive_credibility"), table_name="weather_reports_archive"
    )
    op.create_index(
        "idx_weather_reports_archive_credibility",
        "weather_reports_archive",
        [sa.literal_column("credibility_score DESC")],
        unique=False,
    )
    op.drop_index(
        op.f("idx_weather_reports_archive_status_time"), table_name="weather_reports_archive"
    )
    op.create_index(
        "idx_weather_reports_archive_status_time",
        "weather_reports_archive",
        ["verification_status", sa.literal_column("occurred_at DESC")],
        unique=False,
    )
    op.create_index(
        op.f("ix_weather_reports_archive_external_id"),
        "weather_reports_archive",
        ["external_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_weather_reports_archive_external_id"), table_name="weather_reports_archive"
    )
    op.drop_index("idx_weather_reports_archive_status_time", table_name="weather_reports_archive")
    op.create_index(
        op.f("idx_weather_reports_archive_status_time"),
        "weather_reports_archive",
        ["verification_status", "occurred_at"],
        unique=False,
    )
    op.drop_index("idx_weather_reports_archive_credibility", table_name="weather_reports_archive")
    op.create_index(
        op.f("idx_weather_reports_archive_credibility"),
        "weather_reports_archive",
        ["credibility_score"],
        unique=False,
    )
    op.create_index(op.f("ix_users_email"), "users", ["email"], unique=True)
    op.drop_index(op.f("ix_realtime_outbox_next_retry_at"), table_name="realtime_outbox")
    op.drop_index(op.f("ix_forecast_advisories_valid_until"), table_name="forecast_advisories")
    op.drop_index(op.f("ix_forecast_advisories_valid_from"), table_name="forecast_advisories")
    # ### end Alembic commands ###
