"""Deterministic demo fixture generator for S2 Image Forensics (Item 10).

Provides three SIMULATED scenarios:
1. REUSED_IMAGE: Reused photo across different incidents (CONTRADICTS)
2. EXIF_TIME_MISMATCH: EXIF photo capture timestamp mismatch > 24 hours (CONTRADICTS)
3. NO_EXIF: Photo stripped of EXIF metadata (NEUTRAL, Product Rule P1)

All findings generated by these fixtures are strictly labeled with `is_simulated = True`.
Opt-in via settings.IMAGE_FORENSICS_DEMO_FIXTURE_ENABLED or settings.IMAGE_FORENSICS_ENABLED.
"""

from __future__ import annotations

import logging
import uuid
from datetime import datetime, timedelta, timezone
from typing import Dict, List, Optional

from sqlalchemy.ext.asyncio import AsyncSession

from app.core.config import settings
from app.intelligence.image_forensics import (
    ForensicCheckResult,
    ForensicVerdict,
)
from app.models.image_forensics import IncidentImageFinding
from app.models.media import ReportMedia
from app.models.outbox import RealtimeOutbox
from app.models.report import WeatherReport

logger = logging.getLogger(__name__)

SCENARIO_REUSED_IMAGE = "REUSED_IMAGE"
SCENARIO_EXIF_TIME_MISMATCH = "EXIF_TIME_MISMATCH"
SCENARIO_NO_EXIF = "NO_EXIF"

VALID_DEMO_SCENARIOS = {
    SCENARIO_REUSED_IMAGE,
    SCENARIO_EXIF_TIME_MISMATCH,
    SCENARIO_NO_EXIF,
}


def is_demo_forensics_enabled() -> bool:
    """Check if demo forensics fixtures are allowed by configuration."""
    return bool(
        getattr(settings, "IMAGE_FORENSICS_DEMO_FIXTURE_ENABLED", False)
        or getattr(settings, "IMAGE_FORENSICS_ENABLED", False)
    )


async def create_demo_image_forensics_scenario(
    db: AsyncSession,
    report: WeatherReport,
    scenario: str,
    other_incident_id: Optional[str] = None,
    force: bool = False,
) -> Optional[IncidentImageFinding]:
    """Create a simulated image forensics finding for an incident under a given scenario.

    Args:
        db: Active SQLAlchemy async session.
        report: Incident WeatherReport to attach finding to.
        scenario: One of 'REUSED_IMAGE', 'EXIF_TIME_MISMATCH', 'NO_EXIF'.
        other_incident_id: Optional other incident UUID string for cross-incident reuse.
        force: Bypass the feature flag check if True.

    Returns:
        Persisted IncidentImageFinding with is_simulated=True, or None if disabled.
    """
    if not force and not is_demo_forensics_enabled():
        logger.info("Demo image forensics skipped: neither IMAGE_FORENSICS_ENABLED nor IMAGE_FORENSICS_DEMO_FIXTURE_ENABLED is true.")
        return None

    if scenario not in VALID_DEMO_SCENARIOS:
        raise ValueError(f"Unknown demo scenario '{scenario}'. Must be one of {VALID_DEMO_SCENARIOS}")

    report_id = report.id
    target_time = report.occurred_at or datetime.now(timezone.utc)
    if target_time.tzinfo is None:
        target_time = target_time.replace(tzinfo=timezone.utc)

    # 1. Ensure report has a demo ReportMedia record
    media_id = uuid.uuid4()
    media_key = f"demo/simulated_{scenario.lower()}_{report_id}.jpg"
    sha256 = f"demo{uuid.uuid4().hex[:56]}"

    demo_media = ReportMedia(
        id=media_id,
        report_id=report_id,
        media_type="IMAGE",
        storage_bucket="demo-weather-evidence",
        storage_key=media_key,
        mime_type="image/jpeg",
        file_size_bytes=64000,
        sha256_hash=sha256,
    )
    db.add(demo_media)

    # 2. Build scenario checks and verdict
    cap = float(getattr(settings, "IMAGE_FORENSICS_CAP", 0.05))

    if scenario == SCENARIO_REUSED_IMAGE:
        matched_id = other_incident_id or str(uuid.uuid4())
        checks = [
            ForensicCheckResult(
                check_type="EXIF_TIME",
                verdict=ForensicVerdict.SUPPORTS,
                observed_value=target_time.isoformat(),
                expected_value=target_time.isoformat(),
                difference="0.10 hours",
                reason="EXIF capture timestamp is consistent with incident window",
            ).model_dump(),
            ForensicCheckResult(
                check_type="EXIF_LOCATION",
                verdict=ForensicVerdict.SUPPORTS,
                observed_value="COORDINATES_PRESENT",
                expected_value="DECLARED_INCIDENT_LOCATION",
                difference="1.20 km",
                reason="EXIF GPS coordinates match declared location within 1.20 km",
            ).model_dump(),
            ForensicCheckResult(
                check_type="IMAGE_REUSE",
                verdict=ForensicVerdict.CONTRADICTS,
                observed_value="1 distant matches",
                expected_value="0 cross-incident matches",
                difference="1 distant incident(s)",
                reason=f"Perceptual hash match with separate past incident {matched_id}",
                matched_incident_ids=[matched_id],
            ).model_dump(),
        ]
        finding = IncidentImageFinding(
            id=uuid.uuid4(),
            incident_id=report_id,
            media_id=media_id,
            sha256=sha256,
            phash="a1b2c3d4e5f60000",
            dhash="0000111122223333",
            has_exif=True,
            exif_timestamp_utc=target_time,
            timezone_assumed_ist=False,
            time_verdict=ForensicVerdict.SUPPORTS.value,
            time_difference="0.10 hours",
            location_verdict=ForensicVerdict.SUPPORTS.value,
            location_difference="1.20 km",
            reuse_verdict=ForensicVerdict.CONTRADICTS.value,
            matched_incident_ids=[matched_id],
            overall_verdict=ForensicVerdict.CONTRADICTS.value,
            credibility_adjustment=-cap,
            checks=checks,
            is_simulated=True,
        )

    elif scenario == SCENARIO_EXIF_TIME_MISMATCH:
        mismatch_time = target_time - timedelta(days=5)
        checks = [
            ForensicCheckResult(
                check_type="EXIF_TIME",
                verdict=ForensicVerdict.CONTRADICTS,
                observed_value=mismatch_time.isoformat(),
                expected_value=target_time.isoformat(),
                difference="120.00 hours",
                reason="EXIF photo capture timestamp is 120.00 hours prior to declared incident time (exceeds 24.0h limit)",
            ).model_dump(),
            ForensicCheckResult(
                check_type="EXIF_LOCATION",
                verdict=ForensicVerdict.NEUTRAL,
                reason="No EXIF GPS metadata present in photo (P1)",
            ).model_dump(),
            ForensicCheckResult(
                check_type="IMAGE_REUSE",
                verdict=ForensicVerdict.SUPPORTS,
                reason="No cross-incident reuse detected",
            ).model_dump(),
        ]
        finding = IncidentImageFinding(
            id=uuid.uuid4(),
            incident_id=report_id,
            media_id=media_id,
            sha256=sha256,
            phash="b2c3d4e5f60000a1",
            dhash="1111222233334444",
            has_exif=True,
            exif_timestamp_utc=mismatch_time,
            timezone_assumed_ist=False,
            time_verdict=ForensicVerdict.CONTRADICTS.value,
            time_difference="120.00 hours",
            location_verdict=ForensicVerdict.NEUTRAL.value,
            location_difference=None,
            reuse_verdict=ForensicVerdict.SUPPORTS.value,
            matched_incident_ids=[],
            overall_verdict=ForensicVerdict.CONTRADICTS.value,
            credibility_adjustment=-cap,
            checks=checks,
            is_simulated=True,
        )

    else:  # SCENARIO_NO_EXIF
        checks = [
            ForensicCheckResult(
                check_type="EXIF_TIME",
                verdict=ForensicVerdict.NEUTRAL,
                reason="Missing or stripped EXIF metadata is treated as neutral (P1)",
            ).model_dump(),
            ForensicCheckResult(
                check_type="EXIF_LOCATION",
                verdict=ForensicVerdict.NEUTRAL,
                reason="Missing or stripped EXIF metadata is treated as neutral (P1)",
            ).model_dump(),
            ForensicCheckResult(
                check_type="IMAGE_REUSE",
                verdict=ForensicVerdict.SUPPORTS,
                reason="No cross-incident reuse detected",
            ).model_dump(),
        ]
        finding = IncidentImageFinding(
            id=uuid.uuid4(),
            incident_id=report_id,
            media_id=media_id,
            sha256=sha256,
            phash="c3d4e5f60000a1b2",
            dhash="2222333344445555",
            has_exif=False,
            exif_timestamp_utc=None,
            timezone_assumed_ist=False,
            time_verdict=ForensicVerdict.NEUTRAL.value,
            time_difference=None,
            location_verdict=ForensicVerdict.NEUTRAL.value,
            location_difference=None,
            reuse_verdict=ForensicVerdict.SUPPORTS.value,
            matched_incident_ids=[],
            overall_verdict=ForensicVerdict.NEUTRAL.value,
            credibility_adjustment=0.0,
            checks=checks,
            is_simulated=True,
        )

    db.add(finding)

    # 3. Stage outbox event with is_simulated=True
    outbox = RealtimeOutbox(
        event_id=uuid.uuid4(),
        event_type="incident.image_forensics_completed",
        entity_id=str(report.id),
        tracking_id=report.tracking_id,
        occurred_at=datetime.now(timezone.utc),
        payload={
            "incident_id": str(report.id),
            "tracking_id": report.tracking_id,
            "overall_verdict": finding.overall_verdict,
            "credibility_adjustment": finding.credibility_adjustment,
            "image_count": 1,
            "is_simulated": True,
            "images": [
                {
                    "media_id": str(media_id),
                    "sha256": finding.sha256,
                    "phash": finding.phash,
                    "has_exif": finding.has_exif,
                    "time_verdict": finding.time_verdict,
                    "location_verdict": finding.location_verdict,
                    "reuse_verdict": finding.reuse_verdict,
                    "overall_verdict": finding.overall_verdict,
                    "matched_incident_ids": finding.matched_incident_ids or [],
                }
            ],
        },
        status="PENDING",
        attempts=0,
        max_attempts=5,
    )
    db.add(outbox)

    return finding
