#!/usr/bin/env bash
# scripts/demo-up.sh — Start the isolated SIH demo stack
# Usage: ./scripts/demo-up.sh [extra docker compose args]
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_ROOT="$(dirname "$SCRIPT_DIR")"
ENV_FILE="$PROJECT_ROOT/.env.demo"
COMPOSE_FILE="$PROJECT_ROOT/docker-compose.demo.yml"

# ── Generate .env.demo if missing ─────────────────────────────────────────────
if [[ ! -f "$ENV_FILE" ]]; then
  echo "[demo-up] Generating $ENV_FILE with random secrets..."

  SECRET_KEY=$(python3 -c "import secrets; print(secrets.token_hex(32))")
  DB_PASSWORD=$(python3 -c "import secrets; print(secrets.token_urlsafe(16))")
  MINIO_PASSWORD=$(python3 -c "import secrets; print(secrets.token_urlsafe(16))")

  cat > "$ENV_FILE" <<EOF
# Auto-generated by scripts/demo-up.sh — DO NOT COMMIT
SECRET_KEY=${SECRET_KEY}

POSTGRES_DB=weather_demo
POSTGRES_USER=weather_demo
POSTGRES_PASSWORD=${DB_PASSWORD}

MINIO_ROOT_USER=demoadmin
MINIO_ROOT_PASSWORD=${MINIO_PASSWORD}
S3_BUCKET_NAME=weather-media

ENVIRONMENT=production
DEBUG=false
ALLOWED_ORIGINS=http://localhost:8080
EOF

  echo "[demo-up] Created $ENV_FILE"
else
  echo "[demo-up] Using existing $ENV_FILE"
fi

# ── Start the stack ───────────────────────────────────────────────────────────
echo "[demo-up] Starting demo stack..."
docker compose \
  -f "$COMPOSE_FILE" \
  --env-file "$ENV_FILE" \
  --project-name sih-demo \
  up -d --build "$@"

echo "[demo-up] Stack started. Web UI: http://localhost:8080"
echo "[demo-up] Run: docker compose -f docker-compose.demo.yml -p sih-demo logs -f"
echo "[demo-up] Seed demo data: ./scripts/demo-seed.sh"
